site_name: textX

site_description: A meta-language for building Domain-Specific Languages (DSLs)
site_author: Igor Dejanović

repo_url: https://github.com/textX/textX
google_analytics: [UA-68681917-1, igordejanovic.net]
theme: readthedocs
extra_css: [style.css, css/version-select.css]

nav:
- Home: index.md
- User Guide:
  - Grammar: grammar.md
  - Meta-model: metamodel.md
  - Model: model.md
  - Scoping: scoping.md
  - Multi meta-model: multimetamodel.md
  - Parser configuration: parser_config.md
  - Visualization: visualization.md
  - Error handling: error_handling.md
  - Debugging: debugging.md
  - textx command: textx_command.md
- Tutorials:
  - Hello World: tutorials/hello_world.md
  - Robot: tutorials/robot.md
  - Entity: tutorials/entity.md
  - State Machine: tutorials/state_machine.md
  - Toy language compiler: tutorials/toylanguage.md
  - self-dsl: tutorials/self-dsl.md
- About:
  - Comparison: about/comparison.md
  - Discuss: about/discuss.md
  - Contributing: https://github.com/textX/textX/blob/master/CONTRIBUTING.md
  - License: https://github.com/textX/textX/blob/master/LICENSE.txt

markdown_extensions:
- admonition:
- toc:
    permalink: true

copyright: Copyright &copy; <a href="http://igordejanovic.net/">Igor Dejanović</a>.

extra_javascript:
- js/version-select.js
